# Generated by Django 3.1.6 on 2021-09-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210911_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
