# Generated by Django 3.1.6 on 2021-09-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20210911_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
