# Generated by Django 3.1.6 on 2021-09-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='login_session',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Login Session'),
        ),
    ]
