# Generated by Django 3.1.6 on 2021-09-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20210915_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
