# Generated by Django 3.1.6 on 2021-09-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
